# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'low-effort-sensing' do
end

target 'low-effort-sensing WatchKit App' do

end

target 'low-effort-sensing WatchKit Extension' do

end

